### ISSUE TITLE
Can not make doc html file

### ISSUE THREAD

**Issue by ynchiu** [oseledets/ttpy#41]
I failed making the html file, I wonder if the doc source file should be updated. When I try `make html`, some errors were raised.
`WARNING: /home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/doc/corettutils.rst:29: (WARNING/2) autodoc: failed to import class 'tensor' from module 'tt'; the following exception was raised:
Traceback (most recent call last):
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/__init__.py", line 5, in <module>
    from .core.tt import *
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/tt.py", line 5, in <module>
    from .matrix import matrix
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/matrix.py", line 5, in <module>
    from . import core_f90 as _core_f90
ImportError: cannot import name 'core_f90'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gxzhou/anaconda3/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/__init__.py", line 18, in <module>
    from .core.tt import *
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/tt.py", line 5, in <module>
    from .matrix import matrix
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/matrix.py", line 5, in <module>
    from . import core_f90 as _core_f90
ImportError: cannot import name 'core_f90'
WARNING: /home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/doc/corettutils.rst:36: (WARNING/2) autodoc: failed to import module 'tt'; the following exception was raised:
Traceback (most recent call last):
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/__init__.py", line 5, in <module>
    from .core.tt import *
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/tt.py", line 5, in <module>
    from .matrix import matrix
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/matrix.py", line 5, in <module>
    from . import core_f90 as _core_f90
ImportError: cannot import name 'core_f90'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gxzhou/anaconda3/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/__init__.py", line 18, in <module>
    from .core.tt import *
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/tt.py", line 5, in <module>
    from .matrix import matrix
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/matrix.py", line 5, in <module>
    from . import core_f90 as _core_f90
ImportError: cannot import name 'core_f90'
WARNING: /home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/doc/corettutils.rst:42: (WARNING/2) autodoc: failed to import module 'tt'; the following exception was raised:
Traceback (most recent call last):
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/__init__.py", line 5, in <module>
    from .core.tt import *
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/tt.py", line 5, in <module>
    from .matrix import matrix
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/matrix.py", line 5, in <module>
    from . import core_f90 as _core_f90
ImportError: cannot import name 'core_f90'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gxzhou/anaconda3/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/__init__.py", line 18, in <module>
    from .core.tt import *
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/tt.py", line 5, in <module>
    from .matrix import matrix
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/matrix.py", line 5, in <module>
    from . import core_f90 as _core_f90
ImportError: cannot import name 'core_f90'
WARNING: /home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/doc/corettutils.rst:56: (WARNING/2) autodoc: failed to import class 'matrix' from module 'tt'; the following exception was raised:
Traceback (most recent call last):
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/__init__.py", line 5, in <module>
    from .core.tt import *
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/tt.py", line 5, in <module>
    from .matrix import matrix
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/matrix.py", line 5, in <module>
    from . import core_f90 as _core_f90
ImportError: cannot import name 'core_f90'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gxzhou/anaconda3/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/__init__.py", line 18, in <module>
    from .core.tt import *
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/tt.py", line 5, in <module>
    from .matrix import matrix
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/matrix.py", line 5, in <module>
    from . import core_f90 as _core_f90
ImportError: cannot import name 'core_f90'
WARNING: /home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/doc/corettutils.rst:62: (WARNING/2) autodoc: failed to import module 'tt'; the following exception was raised:
Traceback (most recent call last):
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/__init__.py", line 5, in <module>
    from .core.tt import *
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/tt.py", line 5, in <module>
    from .matrix import matrix
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/matrix.py", line 5, in <module>
    from . import core_f90 as _core_f90
ImportError: cannot import name 'core_f90'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gxzhou/anaconda3/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/__init__.py", line 18, in <module>
    from .core.tt import *
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/tt.py", line 5, in <module>
    from .matrix import matrix
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/matrix.py", line 5, in <module>
    from . import core_f90 as _core_f90
ImportError: cannot import name 'core_f90'
WARNING: /home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/doc/tensorintro.rst:4: (WARNING/2) autodoc: failed to import module 'tt'; the following exception was raised:
Traceback (most recent call last):
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/__init__.py", line 5, in <module>
    from .core.tt import *
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/tt.py", line 5, in <module>
    from .matrix import matrix
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/matrix.py", line 5, in <module>
    from . import core_f90 as _core_f90
ImportError: cannot import name 'core_f90'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gxzhou/anaconda3/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/__init__.py", line 18, in <module>
    from .core.tt import *
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/tt.py", line 5, in <module>
    from .matrix import matrix
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/matrix.py", line 5, in <module>
    from . import core_f90 as _core_f90
ImportError: cannot import name 'core_f90'
WARNING: /home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/doc/ttalgorithms.rst:4: (WARNING/2) autodoc: failed to import function 'multifuncrs' from module 'tt'; the following exception was raised:
Traceback (most recent call last):
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/__init__.py", line 5, in <module>
    from .core.tt import *
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/tt.py", line 5, in <module>
    from .matrix import matrix
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/matrix.py", line 5, in <module>
    from . import core_f90 as _core_f90
ImportError: cannot import name 'core_f90'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gxzhou/anaconda3/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/__init__.py", line 18, in <module>
    from .core.tt import *
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/tt.py", line 5, in <module>
    from .matrix import matrix
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/matrix.py", line 5, in <module>
    from . import core_f90 as _core_f90
ImportError: cannot import name 'core_f90'
WARNING: /home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/doc/ttalgorithms.rst:6: (WARNING/2) autodoc: failed to import function 'amen_solve' from module 'tt.amen'; the following exception was raised:
Traceback (most recent call last):
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/__init__.py", line 5, in <module>
    from .core.tt import *
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/tt.py", line 5, in <module>
    from .matrix import matrix
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/matrix.py", line 5, in <module>
    from . import core_f90 as _core_f90
ImportError: cannot import name 'core_f90'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gxzhou/anaconda3/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/__init__.py", line 18, in <module>
    from .core.tt import *
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/tt.py", line 5, in <module>
    from .matrix import matrix
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/matrix.py", line 5, in <module>
    from . import core_f90 as _core_f90
ImportError: cannot import name 'core_f90'
WARNING: /home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/doc/ttalgorithms.rst:8: (WARNING/2) autodoc: failed to import function 'rect_cross' from module 'tt.cross'; the following exception was raised:
Traceback (most recent call last):
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/__init__.py", line 5, in <module>
    from .core.tt import *
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/tt.py", line 5, in <module>
    from .matrix import matrix
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/matrix.py", line 5, in <module>
    from . import core_f90 as _core_f90
ImportError: cannot import name 'core_f90'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gxzhou/anaconda3/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/__init__.py", line 18, in <module>
    from .core.tt import *
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/tt.py", line 5, in <module>
    from .matrix import matrix
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/matrix.py", line 5, in <module>
    from . import core_f90 as _core_f90
ImportError: cannot import name 'core_f90'
WARNING: /home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/doc/ttalgorithms.rst:10: (WARNING/2) autodoc: failed to import function 'eigb' from module 'tt.eigb'; the following exception was raised:
Traceback (most recent call last):
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/__init__.py", line 5, in <module>
    from .core.tt import *
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/tt.py", line 5, in <module>
    from .matrix import matrix
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/matrix.py", line 5, in <module>
    from . import core_f90 as _core_f90
ImportError: cannot import name 'core_f90'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gxzhou/anaconda3/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/__init__.py", line 18, in <module>
    from .core.tt import *
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/tt.py", line 5, in <module>
    from .matrix import matrix
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/matrix.py", line 5, in <module>
    from . import core_f90 as _core_f90
ImportError: cannot import name 'core_f90'
WARNING: /home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/doc/ttalgorithms.rst:12: (WARNING/2) autodoc: failed to import function 'ksl' from module 'tt.ksl'; the following exception was raised:
Traceback (most recent call last):
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/__init__.py", line 5, in <module>
    from .core.tt import *
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/tt.py", line 5, in <module>
    from .matrix import matrix
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/matrix.py", line 5, in <module>
    from . import core_f90 as _core_f90
ImportError: cannot import name 'core_f90'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gxzhou/anaconda3/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/__init__.py", line 18, in <module>
    from .core.tt import *
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/tt.py", line 5, in <module>
    from .matrix import matrix
  File "/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/core/matrix.py", line 5, in <module>
    from . import core_f90 as _core_f90
ImportError: cannot import name 'core_f90'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] ttalgorithms
WARNING: LaTeX command 'latex' cannot be run (needed for math display), check the pngmath_latex setting
generating indices... genindex
writing additional pages... search
copying static files... WARNING: html_static_path entry '/home/gxzhou/YuningQiu/Learning/TensorflowCode/ttpy/tt/doc/_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 14 warnings.

Build finished. The HTML pages are in _build/html.`

**Comment by daskol** [comment]
The reason why `make html` failed is that you should build project at first. When one tries to assembly doc the build script imports all modules of `ttpy` package including native dependencies like core libs written in Fortran or BLAS. See installation guide in [README](/oseledets/ttpy#installation) for details.

You can try [this one](https://daskol.xyz/doc/oseledets/ttpy/) assembled by me for my own purposes. Although official doc on [ReadTheDocs](https://readthedocs.org) is more preferable.

@oseledets Can you deploy documentaion on [ReadTheDocs](https://readthedocs.org) under your account since you is project owner and maintainer?
